### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by bsian03** [abalabahaha/eris#1464]
Happy new year! It's been a while (actually, a long while) since the last commit. I've recently had some time to get back into Discord development so want to get Eris back to its former glory. Obviously this means updating the library to match Discord's current API state.
I need some help though. With so much that has happened on Discord, I'm definitely going to miss something. So serve this as a tracker for stuff that needs updating which does **not** already have a PR open.
Leave anything that needs updating in the comments and I'll add it to the list, and if you can, please create a PR!

- [x] Client#createCommand `type` option needs to be prefixed with `command.` in JSDoc
- [ ] Unify the file parameter behaviour for sending/editing messages and webhooks. Also rename to `files`
- [x] Text in stage
  - #1485
- [x] Make sure everything is sorted alphabetically
  - #1466 
- [x] Simplify channel classes?
- [x] Forum channels
  - #1452
- [x] Media channels
  - #1486
- [ ] Application Command/Interaction Attachment option, discord/discord-api-docs#6272
  - #1358 (may require redoing)
- [x] POST [Modify Guild MFA Level](https://discord.dev/resources/guild#modify-guild-mfa-level)
  - #1473
- [x] Update select menu discord/discord-api-docs#5543 discord/discord-api-docs#6442
  - #1560
- [x] Proper group channel support in line with API
  - #1485 clash #1338
- [x] Onboarding feature (Get, Modify, Onboarding object, member flag
  - #1478
- [x] Soundboard discord/discord-api-docs#6260 discord/discord-api-docs#6025
  - #1550 #1547
- [x] [Role Tags](https://discord.dev/topics/permissions#role-object-role-tags-structure)
  - #1474
- [x] Guild Audit Log Entry [Create Event](https://discord.dev/topics/gateway-events#guild-audit-log-entry-create)
  - #1481
- [x] Automod things discord/discord-api-docs#5778 discord/discord-api-docs#6558
  - #1556
- [x] Role connections discord/discord-api-docs#5668
- [x] Thread member pagination discord/discord-api-docs#5834
- [x] Avatar Decorations discord/discord-api-docs#6464
  - #1471 
- [x] Bot activity state discord/discord-api-docs#6345
  - #1475
- [x] discord/discord-api-docs#6559
  - #1546
- [x] Voice Channel Status discord/discord-api-docs#6400 discord/discord-api-docs#6398
- [ ] discord/discord-api-docs#6396
- [x] discord/discord-api-docs#6377
  - Included in #1470
- [ ] discord/discord-api-docs#6285 maybe?
- [ ] Entitlements https://discord.dev/resources/entitlement
  - #1555
- [ ] App Subscriptions https://discord.dev/monetization/implementing-app-subscriptions
- [x] discord/discord-api-docs#6577
  - #1554
- [ ] discord/discord-api-docs#6650 relevant?
- [x] discord/discord-api-docs#6647
  - #1553
- [ ] DAVE https://discord.dev/topics/voice-connections
- [x] discord/discord-api-docs#6717 to be added to oldMember
  - #1569
- [ ] Everything under the Application page?
- [x] discord/discord-api-docs#6864
  - #1570
- [ ] discord/discord-api-docs#6870
  - #1532
- [x] discord/discord-api-docs#6913
  - #1571
- [x] discord/discord-api-docs#6927
  - #1572
- [x] discord/discord-api-docs#7033 (name change only)
  - #1566
- [x] discord/discord-api-docs#7050
  - #1573
- [x] discord/discord-api-docs#7058 discord/discord-api-docs#7062
  - #1574
- [x] discord/discord-api-docs#7061
  - #1575
- [x] discord/discord-api-docs#7065
  - #1576
- [x] discord/discord-api-docs#7074
  - #1577
- [x] discord/discord-api-docs#7090
  - #1578
- [x] discord/discord-api-docs#7113
  - #1579
- [x] discord/discord-api-docs#7114 maybe?
  - #1580
- [ ] discord/discord-api-docs#7115 to investigate
- [ ] discord/discord-api-docs#7116
- [ ] discord/discord-api-docs#7129
- [ ] discord/discord-api-docs#7232
- [ ] discord/discord-api-docs#7233
- [ ] newly_created on THREAD_CREATE event (bool)
- [ ] discord/discord-api-docs#6265 requires deprecation of getNitroStickerPacks
- [ ] discord/discord-api-docs#7253
- [ ] discord/discord-api-docs#7267

This list is ***NOT*** exhaustive

**Comment by SleepyYui** [comment]
Another addition would be to support forum tags and general [changes done to the channels](https://discord.com/developers/docs/resources/channel) such as supporting stage chat and forums (especially tags)

**Comment by bsian03** [comment]
> Another addition would be to support forum tags and general [changes done to the channels](https://discord.com/developers/docs/resources/channel) such as supporting stage chat and forums (especially tags)
> 

I've added forum tags. Text in stage is already in the list of things to do

**Comment by SleepyYui** [comment]
> > Another addition would be to support forum tags and general [changes done to the channels](https://discord.com/developers/docs/resources/channel) such as supporting stage chat and forums (especially tags)
> 
> I've added forum tags. Text in stage is already in the list of things to do

I'm working on the [forum stuff](https://github.com/SleepyYui/eris/tree/forum-support) currently

**Comment by conorwastakenwastaken** [comment]
> > > Another addition would be to support forum tags and general [changes done to the channels](https://discord.com/developers/docs/resources/channel) such as supporting stage chat and forums (especially tags)
> > 
> > 
> > I've added forum tags. Text in stage is already in the list of things to do
> 
> I'm working on the [forum stuff](https://github.com/SleepyYui/eris/tree/forum-support) currently

@SleepyYui Ive got a draft PR open to add forum channel support (#1452). I opened it a while back and then stopped working on it cuz Eris died lol. If you wanna work on forums instead then I'll close mine

**Comment by bsian03** [comment]
Include it in that PR please

**Comment by SleepyYui** [comment]
> > > > Another addition would be to support forum tags and general [changes done to the channels](https://discord.com/developers/docs/resources/channel) such as supporting stage chat and forums (especially tags)
> > > 
> > > 
> > > I've added forum tags. Text in stage is already in the list of things to do
> > 
> > 
> > I'm working on the [forum stuff](https://github.com/SleepyYui/eris/tree/forum-support) currently
> 
> @SleepyYui Ive got a draft PR open to add forum channel support (#1452). I opened it a while back and then stopped working on it cuz Eris died lol. If you wanna work on forums instead then I'll close mine

@iiFDCT Yours looks great, I'll just work on something different instead or just contribute to your branch (Maybe PR to your fork?) if you have lost interest in finishing that

**Comment by bsian03** [comment]
discord/discord-api-docs#6577 
discord/discord-api-docs#6650 relevant?
discord/discord-api-docs#6647

**Comment by bsian03** [comment]
discord/discord-api-docs#6559
discord/discord-api-docs#6558
discord/discord-api-docs#6484 maybe?
discord/discord-api-docs#6464
discord/discord-api-docs#6400
discord/discord-api-docs#6398
discord/discord-api-docs#6396
discord/discord-api-docs#6377 maybe?
discord/discord-api-docs#6285 maybe?

**Comment by conorwastakenwastaken** [comment]
> discord/discord-api-docs#6377 maybe?

I've added `#6377` in with super reactions (#1470)

**Comment by flav-code** [comment]
#1527

**Comment by bsian03** [comment]
I just updated the main post with a bunch of stuff that still needs doing. Bear in mind there may still be missing items not included in the list. If you find one, please let me know (some are sent directly to relevant PRs)

**Comment by areodot** [comment]
Please add https://github.com/abalabahaha/eris/pull/1567

**Comment by conorwastakenwastaken** [comment]
I've created #1596 so you can reference that in your initial comment
